PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Error.cshtml.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PluralSightOdeToFood.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PluralSightOdeToFood.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace PluralSightOdeToFood.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Restaurants/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace PluralSightOdeToFood.Pages.Restaurants
{
    public class DeleteModel : PageModel
    {
        public Restaurant Restaurant { get; set; }
        private readonly IRestaurantData _restaurantData;

        public DeleteModel(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = _restaurantData.GetById(restaurantId);
            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }

        public IActionResult OnPost(int restaurantId)
        {
            var restaurant = _restaurantData.Delete(restaurantId);
            _restaurantData.Commit();

            if (restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }

            TempData["Message"] = $"{restaurant.Name} has been deleted!";
            return RedirectToPage("./List");
        }
    }
}

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Restaurants/Detail.cshtml.cs
using System.Reflection.Metadata;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OdeToFood.Core;
using OdeToFood.Data;

namespace PluralSightOdeToFood.Pages.Restaurants
{
    public class Detail : PageModel
    {
        private readonly IRestaurantData _restaurantData;
        public Restaurant Restaurant { get; set; }
        [TempData]
        public string Message { get; set; }

        public Detail(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }
        
        public IActionResult OnGet(int restaurantId)
        {
            Restaurant = _restaurantData.GetById(restaurantId);
            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }
            return Page();
        }
    }
}

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Restaurants/Edit.cshtml.cs
using System.Collections;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using OdeToFood.Core;
using OdeToFood.Data;

namespace PluralSightOdeToFood.Pages.Restaurants
{
    public class Edit : PageModel
    {
        private readonly IRestaurantData _restaurantData;
        private readonly IHtmlHelper _htmlHelper;
        [BindProperty] public Restaurant Restaurant { get; set; }
        public IEnumerable<SelectListItem> Cuisines { get; set; }

        public Edit(IRestaurantData restaurantData, IHtmlHelper htmlHelper)
        {
            _restaurantData = restaurantData;
            _htmlHelper = htmlHelper;
        }
        
        public IActionResult OnGet(int? restaurantId)
        {
            Cuisines = _htmlHelper.GetEnumSelectList<CuisineType>();
            if (restaurantId.HasValue)
            {
                Restaurant = _restaurantData.GetById(restaurantId.Value);
            }
            else
            {
                Restaurant = new Restaurant();
            }
            if (Restaurant == null)
            {
                return RedirectToPage("./NotFound");
            }

            return Page();
        }

        public IActionResult OnPost()
        {
            if (!ModelState.IsValid)
            {
                Cuisines = _htmlHelper.GetEnumSelectList<CuisineType>();
                return Page();
            }

            // this relies on the db not using 0 as a record id value
            if (Restaurant.Id > 0)
            {
                _restaurantData.Update(Restaurant);
            }
            else
            {
                _restaurantData.Add(Restaurant);
            }
            _restaurantData.Commit();
            
            // TempData is provided by ASPNet.Core to store temporary data. Gets reset on next page load
            TempData["Message"] = "Restaurant saved!";

            // the anonymous object will pass the restaurant id through to the Details page
            // PRG pattern => POST Response GET i.e redirect to a GET request once success POST has been made
            return RedirectToPage("./Detail", new { restaurantId = Restaurant.Id });
        }
    }
}

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Restaurants/List.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using OdeToFood.Core;
using OdeToFood.Data;

namespace PluralSightOdeToFood.Pages.Restaurants
{
    public class ListModel : PageModel
    {
        private readonly IConfiguration _config;
        private readonly IRestaurantData _restaurantData;
        public string Message { get; set; }
        
        // tells project to look for SearchTerm in the http request before calling OnGet
        // by default only supports POST but can modify as shown
        [BindProperty(SupportsGet = true)] public string SearchTerm { get; set; }
        
        public IEnumerable<Restaurant> Restaurants { get; set; }

        public ListModel(IConfiguration config, IRestaurantData restaurantData)
        {
            _config = config;
            _restaurantData = restaurantData;
        }
        
        public void OnGet(string searchTerm)
        {
            // Hard coded message
            // Message = "Hello, world!";
            // Message pulled through from appsettings.json
            Message = _config.GetValue<string>("Message");
            Restaurants = _restaurantData.GetRestaurantsByName(SearchTerm);
        }
    }
}

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/ViewComponents/RestaurantCountViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using OdeToFood.Data;

namespace PluralSightOdeToFood.ViewComponents
{
    public class RestaurantCountViewComponent : ViewComponent
    {
        private readonly IRestaurantData _restaurantData;

        public RestaurantCountViewComponent(IRestaurantData restaurantData)
        {
            _restaurantData = restaurantData;
        }

        public IViewComponentResult Invoke()
        {
            var count = _restaurantData.GetCountOfRestaurants();
            return View(count);
        }
    }
}

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Restaurants/Delete.cshtml
@page "{restaurantId}"
@model PluralSightOdeToFood.Pages.Restaurants.DeleteModel
@{
}

<h2>Delete!</h2>
<div class="alert alert-danger">
    Are you sure you want to delete @Model.Restaurant.Name?
</div>
<form method="post">
    <button type="submit" class="alert-danger">Yes!</button>
    <a asp-page="List" class="btn btn-primary">Cancel</a>
</form>

@* default layout taken from the layout specified in _ViewStart *@

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Restaurants/Detail.cshtml
@* set the url route to Restaurants/Detail/ and then a variable called restuarantId *@
@page "{restaurantId:int}"
@model PluralSightOdeToFood.Pages.Restaurants.Detail

@{
    ViewData["Title"] = "Detail";
}

<!DOCTYPE html>

<html>
<head>
    <title>Restaurant Detail</title>
</head>
<body>
@if (Model.Message != null)
{
    <div class="alert alert-info">@Model.Message</div>
}
<div>
    <h2>@Model.Restaurant.Name</h2>
</div>
<div>
    Id: @Model.Restaurant.Id
</div>
<div>
    Location: @Model.Restaurant.Location
</div>
<div>
    Cuisine: @Model.Restaurant.Cuisine
</div>

<a asp-page="./List" class="btn btn-outline-info">All Restaurants</a>
</body>
</html>

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Restaurants/Edit.cshtml
@page "{restaurantId:int?}"
@using OdeToFood.Core
@model PluralSightOdeToFood.Pages.Restaurants.Edit

@{
    ViewData["Title"] = "Edit";
}

<!DOCTYPE html>

<html>
<head>
    <title>Edit</title>
</head>
<body>
<div>
    <h2>Editing @Model.Restaurant.Name</h2>
    <form method="post">
        <input type="hidden" asp-for="Restaurant.Id" />
        <div class="form-group">
            <label asp-for="Restaurant.Name"></label>
            <input asp-for="Restaurant.Name" class="form-control"/>
            <span class="text-danger" asp-validation-for="Restaurant.Name"></span>
        </div>
        <div class="form-group">
            <label asp-for="Restaurant.Location"></label>
            <input asp-for="Restaurant.Location" class="form-control"/>
            <span class="text-danger" asp-validation-for="Restaurant.Location"></span>
        </div>
        <div class="form-group">
            <label asp-for="Restaurant.Cuisine"></label>
            <select class="form-control" asp-for="Restaurant.Cuisine"
                    asp-items="Model.Cuisines"
            >        
            </select>
        </div>
        <button type="submit" class="btn btn-outline-primary">Submit</button>
    </form>
    <span></span>
    <a asp-page="./List">
        <button class="btn btn-outline-info">Restaurant List</button>
    </a>
</div>
</body>
</html>

@* where possible it is better to do this in the page model *@
@* asp-items="Html.GetEnumSelectList<CuisineType>()"> *@

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Restaurants/List.cshtml
@page
@model ListModel

@{
    ViewData["Title"] = "Restaurants";
}

<!DOCTYPE html>

<html>
<head>
    <title>Restaurants</title>
</head>
<body>
<div>
    <h1>@ViewData["Title"]</h1>
    <p>Restaurant List</p>
    <form method="get">
        <div class="form-group">
            <div class="input-group">
                @* because we are using asp-for 'Model.' is assumed unlike in the foreach below. 
                        asp-for is essentially performing a two-way bind between model and form*@
                <input type="search" class="form-control" asp-for="SearchTerm"/>
                <span class="input-group-btn">
                    <button class="btn btn-outline-success">
                        Search
                    </button>
                </span>
            </div>
        </div>
    </form>
    @foreach (var restaurant in Model.Restaurants)
    {
        <partial name="_Summary" model="restaurant"/>
    }
    <a asp-page="./Edit" class="btn btn-primary">Add New</a>
</div>
@section footer
{
    
    <div>@Model.Message</div>
}
</body>
</html>

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Restaurants/NotFound.cshtml
@page

@{
    ViewData["Title"] = "NotFound";
}

<!DOCTYPE html>

<html>
<head>
    <title>Not Found</title>
</head>
<body>
<div>
    <h2>Your restaurant was not found</h2>
    <a asp-page="./List">
        <button class="btn btn-outline-info">Restaurant List</button>
    </a>
</div>
</body>
</html>

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Restaurants/_Summary.cshtml
@model OdeToFood.Core.Restaurant

<div class="card">
    <div class="card-header">
        <h3>@Model.Name</h3>
    </div>
    <div class="card-body">
        <span>Location: @Model.Location</span>
        <span>Cuisine: @Model.Cuisine</span>
    </div>
    <div class="card-footer">
        <a class="btn btn-sm btn-info" asp-page="./Detail" asp-route-restaurantId="@Model.Id">
            Zoom
        </a>
        <a class="btn btn-sm btn-secondary" asp-page="./Edit" asp-route-restaurantId="@Model.Id">
            Edit
        </a>
        <a class="btn btn-sm btn-danger" asp-page="./Delete" asp-route-restaurantId="@Model.Id">
            Delete
        </a>
    </div>
</div>

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Shared/Components/RestaurantCount/Default.cshtml
@model int

<div class="well">
    There are @Model restaurants here. <a asp-page="/Restaurants/List">See them all</a>
</div>

PluralSight_ASPNetCore_Fundamentals/PluralSightOdeToFood/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PluralSightOdeToFood</title>
    <link rel="stylesheet" href="~/lib/css/bootstrap.css" />
    @* <link rel="stylesheet" href="~/css/site.css" /> *@
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">PluralSightOdeToFood</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-danger" asp-area="" asp-page="/Restaurants/List">Restaurants</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

<footer class="border-top footer text-muted">
    <div class="container card-header">
        <vc:restaurant-count></vc:restaurant-count>
        &copy; 2020 - PluralSightOdeToFood - <a asp-area="" asp-page="/Privacy">Privacy</a>
        @RenderSection("footer", required: false)
    </div>
</footer>

    <script src="~/lib/js/jquery-3.4.1.min.js"></script>
    <script src="~/lib/js/bootstrap.bundle.min.js"></script>
    @* <script src="~/js/site.js" asp-append-version="true"></script> *@

    @RenderSection("Scripts", required: false)
</body>
</html>